{% set name = "primod" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/primod-{{ version }}.tar.gz
  sha256: c600d6b45d4c40c08003ff1f3a156bd1d0d6bb40c206a297e05dac92dcca7976

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=61
    - pip
  run:
    - python >=3.10
    - geopandas
    - imod
    - numpy
    - pandas
    - ribasim
    - tomli-w
    - xarray

test:
  imports:
    - primod
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://deltares.github.io/iMOD-Documentation/coupler.html
  summary: Pre-process iMOD Coupler
  dev_url: https://github.com/Deltares/imod_coupler/pre-processing
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Hofer-Julian
    - Huite
    - visr
