{% set name = "primod" %}
{% set version = "2024.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/primod-{{ version }}.tar.gz
  sha256: 73b0b1118fbfedab1204d30bed518d675b9b4bb90ab7ef35085807f29a40ae88

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - hatchling
    - pip
  run:
    - python >=3.10
    - geopandas
    - imod
    - numpy
    - pandas
    - ribasim
    - tomli-w
    - xarray
    - scipy

test:
  imports:
    - primod
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://deltares.github.io/iMOD-Documentation/coupler.html
  summary: Pre-process iMOD Coupler
  dev_url: https://github.com/Deltares/imod_coupler/pre-processing
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Hofer-Julian
    - Huite
    - visr
